In [14]:
# numpy各种方法
import numpy as np

# 1.从TXT文件中读取数据
world_alcohol = np.genfromtxt("world_alcohol.txt",delimiter=",",dtype=str)
print(type(world_alcohol))
print("============")
print(world_alcohol)
print("============")
print(world_alcohol[1:3])
# print(help(np.genfromtxt))

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']]


In [6]:
import numpy as np
# 2.numpy.array
vector = np.array([5,10,15,20])
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(vector,end = '\n\n')
print(matrix)


[ 5 10 15 20]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [15]:
import numpy as np
# 3.shape表示结构
vector = np.array([5,10,15,20])
print(vector.shape)
print("============")
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
print (matrix.shape)

(4,)
(3, 3)


In [16]:
import numpy as np
# numpy.array里面必须是相同的结构
numbers = np.array([1,2,3,4])
print(numbers)
print(numbers.dtype)
print("============")
numbers = np.array([1,2,3,4.0])
print(numbers)
print(numbers.dtype)
print("============")
numbers = np.array([1,2,3,'a'])
print(numbers)
print(numbers.dtype)

[1 2 3 4]
int32
[1. 2. 3. 4.]
float64
['1' '2' '3' 'a']
<U11


In [19]:
import numpy as np
# 取数组元素
world_alcohol = np.genfromtxt("world_alcohol.txt",delimiter=",",dtype=str)
print(world_alcohol)
select = world_alcohol[3][0]#select = world_alcohol[3,0]
select1 = world_alcohol[0:3,0]
print("============")
print(select)
print("============")
print(select1)

[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
1985
['Year' '1986' '1986']


In [22]:
import numpy as np
# 切片
vector = np.array([5,10,15,20])
print(vector[0:3])
print("============")
matrix = np.array([
					[5,10,15],
					[20,25,30],
					[35,40,45],
					[50,55,60]
					])
print(matrix[:, 0:2])#打印每一行的前两个元素
print("============")
print(matrix[1:3, 0:2])#第二行和第三行中前两个元素

[ 5 10 15]
[[ 5 10]
 [20 25]
 [35 40]
 [50 55]]
[[20 25]
 [35 40]]


In [81]:
import numpy as np
# array判断
vector = np.array([5,10,15,20])
print(vector == 10)  #相当于对每一个元素进行了操作
print("============")
matrix = np.array([
					[5,10,15],
					[20,25,30],
					[35,40,45],
					[50,55,60]
					])
print(matrix == 10)
print("------------")
equal_to_ten = (vector == 10)
print(vector[equal_to_ten])#bool类型作为索引
print("============")
second_colum_25 = (matrix[:,1]==25)
print(second_colum_25) #二维数组中 bool索引(行索引)
print("============")
print(matrix[second_colum_25, :])


[False  True False False]
[[False  True False]
 [False False False]
 [False False False]
 [False False False]]
------------
[10]
[False  True False False]
[[20 25 30]]


In [27]:
import numpy as np
# array与或判断
vector = np.array([5,10,15,20])
equal_to_ten_and_five = (vector == 10)&(vector ==5)#逐项比较
print(equal_to_ten_and_five)
print("------------")
equal_to_ten_and_five = (vector == 10)|(vector ==5)
print(equal_to_ten_and_five) 

[False False False False]
[ True  True False False]


In [30]:
import numpy as np
# 对二维数组改变其中的类型，astype
vector = np.array(["1","2","3","4"])
print(vector.dtype)#<U1代表字符型
print("------------")
vector = vector.astype(int)
print(vector.dtype)
print("------------")
print(vector)

<U1
------------
int32
------------
[1 2 3 4]


In [35]:
import numpy as np
# 对array求最小值和最大值min() and max() 求和等操作
vector = np.array([5,10,15,20])
print(vector.min(),'\t',vector.max())
print("------------")
# print(help(np.array)) #查找更多操作
matrix = np.array([
					[5,10,15],
					[20,25,30],
					[35,40,45],
					[50,55,60]
					])
print(matrix.sum())#全部求和
print("------------")
print(matrix.sum(axis = 1))#指定维度求和（按行）
print("============")
print(matrix.sum(axis = 0))#按列
# print(help(np.sum))
print(matrix.max())

5 	 20
------------
390
------------
[ 30  75 120 165]
[110 130 150]
60


In [43]:
import numpy as np
# 初始化矩阵
print(np.arange(15))
print("------------")
a = np.arange(15).reshape(3,5)
print(a,"\n",a.shape,"\n",a.dtype)
print("============")
print(a.ndim)#维度
print("------------")
print(a.size)#元素个数


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 
 (3, 5) 
 int32
2
------------
15


In [45]:
import numpy as np
b = np.zeros([3,4])    #b = np.zeros((3,4))也对
print(b)
print("============")
print(np.ones((2,3,4),dtype = np.int))
print("------------")
print(np.arange(1,20,5))
print("============")
np.arange(12).reshape(3,4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
------------
[ 1  6 11 16]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
import numpy as np
# random初始化
c = np.random.random((2,3))
c = np.random.random([2,3])
print(c)
print("************")
# linespace均匀取值
d = np.linspace(0,10,5)#0-10之间均匀取5个数
print(d)
print("************")
print(np.sin(d))
print(d.max())

[[0.43946784 0.21771752 0.47420368]
 [0.19458951 0.64099753 0.34668523]]
************
[ 0.   2.5  5.   7.5 10. ]
************
[ 0.          0.59847214 -0.95892427  0.93799998 -0.54402111]
10.0


In [54]:
import numpy as np
# 数学运算
a = np.arange(20,60,10)#20-59之间，间隔为10
print(a)
print("------------")
b = np.arange(4)
print(b)
c = a-b
print("------------")
print(c)
print("************")
print(c-1) #每个位置减一
print("************")
print(b,b**2)
print("************")
print(b^3)#循环列表位移左
print(a<30)
b^(-3)

[20 30 40 50]
------------
[0 1 2 3]
------------
[20 29 38 47]
************
[19 28 37 46]
************
[0 1 2 3] [0 1 4 9]
************
[3 2 1 0]
[ True False False False]


array([-3, -4, -1, -2], dtype=int32)

In [56]:
import numpy as np
A = np.array([
			[1,1],
			[0,1],
			])
B = np.array([
			[2,0],
			[3,4],
			])
print(A,'\n',"------")
print(B,"\n","------")
print(A*B)#对应相乘
print("************")
#矩阵相乘两种方法
print(A.dot(B),"\n","------","\n",np.dot(A,B))
B = np.arange(3)
print("************")
print(B)
print("------------")
print(np.exp(B))
print("------------")
print(np.sqrt(B))

[[1 1]
 [0 1]] 
 ------
[[2 0]
 [3 4]] 
 ------
[[2 0]
 [0 4]]
************
[[5 4]
 [3 4]] 
 ------ 
 [[5 4]
 [3 4]]
************
[0 1 2]
------------
[1.         2.71828183 7.3890561 ]
------------
[0.         1.         1.41421356]


In [60]:
import numpy as np
# floor向下取整
b = 10*np.random.random((3,4))
print(b)
a = np.floor(10*b)
print(a)
print('--------')
print(a.ravel())#把矩阵拉成一维向量
print('------------------')
a.shape = (6,2)
b = a.reshape(4,3)
print(a)
print('-------------------')
print(b)
print('--------')
print(a.T)#转置操作

[[6.42015343 3.85971727 3.47844461 4.86723979]
 [1.0684956  9.75250052 6.72307876 1.4215391 ]
 [0.15998351 9.15020983 5.06060233 5.51877311]]
[[64. 38. 34. 48.]
 [10. 97. 67. 14.]
 [ 1. 91. 50. 55.]]
--------
[64. 38. 34. 48. 10. 97. 67. 14.  1. 91. 50. 55.]
------------------
[[64. 38.]
 [34. 48.]
 [10. 97.]
 [67. 14.]
 [ 1. 91.]
 [50. 55.]]
-------------------
[[64. 38. 34.]
 [48. 10. 97.]
 [67. 14.  1.]
 [91. 50. 55.]]
--------
[[64. 34. 10. 67.  1. 50.]
 [38. 48. 97. 14. 91. 55.]]


In [62]:
import numpy as np
# 矩阵拼接
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print('--------')
print(b)
print('------------------')
c = np.hstack((a,b))#横着拼接
d = np.vstack((a,b))#竖着拼接
print(c)
print('------------------')
print(d)

[[2. 4.]
 [2. 0.]]
--------
[[6. 2.]
 [5. 9.]]
------------------
[[2. 4. 6. 2.]
 [2. 0. 5. 9.]]
------------------
[[2. 4.]
 [2. 0.]
 [6. 2.]
 [5. 9.]]


In [64]:
import numpy as np
# 矩阵分割
a = np.floor(10*np.random.random((2,12)))
print(a)
print('--------')
print(np.hsplit(a,3))#均等切分成三份
print('----------------')
print(np.hsplit(a,(3,5)))#指定切分位置
print('--------')
a = a.T
print(a)
print('-----------------')
print(np.vsplit(a,4))
print('--------')
print(np.vsplit(a,(2,6)))

[[8. 8. 5. 2. 2. 8. 7. 5. 6. 0. 0. 6.]
 [8. 9. 6. 1. 7. 5. 6. 9. 9. 1. 6. 5.]]
--------
[array([[8., 8., 5., 2.],
       [8., 9., 6., 1.]]), array([[2., 8., 7., 5.],
       [7., 5., 6., 9.]]), array([[6., 0., 0., 6.],
       [9., 1., 6., 5.]])]
----------------
[array([[8., 8., 5.],
       [8., 9., 6.]]), array([[2., 2.],
       [1., 7.]]), array([[8., 7., 5., 6., 0., 0., 6.],
       [5., 6., 9., 9., 1., 6., 5.]])]
--------
[[8. 8.]
 [8. 9.]
 [5. 6.]
 [2. 1.]
 [2. 7.]
 [8. 5.]
 [7. 6.]
 [5. 9.]
 [6. 9.]
 [0. 1.]
 [0. 6.]
 [6. 5.]]
-----------------
[array([[8., 8.],
       [8., 9.],
       [5., 6.]]), array([[2., 1.],
       [2., 7.],
       [8., 5.]]), array([[7., 6.],
       [5., 9.],
       [6., 9.]]), array([[0., 1.],
       [0., 6.],
       [6., 5.]])]
--------
[array([[8., 8.],
       [8., 9.]]), array([[5., 6.],
       [2., 1.],
       [2., 7.],
       [8., 5.]]), array([[7., 6.],
       [5., 9.],
       [6., 9.],
       [0., 1.],
       [0., 6.],
       [6., 5.]])]


In [65]:
import numpy as np
# 复制操作，3种方法，等号赋值
a = np.arange(12)
#浅拷贝
b = a 			
print(b is a)
print(b.shape)
b.shape = (3,4)
print(a,id(a))
print('--------')
print(b,id(b))

True
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2729189640032
--------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2729189640032


In [69]:
import numpy as np
#深拷贝,也不完全是深拷贝view()
a = np.arange(12)
c = a.view()
print(c is a)
print('========')
c.shape = (2,6)
print(a.shape)#改变c,a不变
print(id(a),id(c))
print(a)
print('--------')
print(c)
c[1][3] = 100 #c[1][3]对应的元素为9
#a对应的元素9也变成100
#虽然指向的地址空间不同，但共用一套值
print('========')
print(a) 

False
(12,)
2729189818976 2729189819536
[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[  0   1   2   3   4   5   6   7   8 100  10  11]


In [75]:
import numpy as np
# 真正的深拷贝copy()
a1 = np.arange(12)
a1.shape = (3,4)
d = a1.copy()
print(d) 
print('--------')
print("",id(a1),"\n",id(d))
print('--------')
d[0,0] = 1111
print(d)
print('========')
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------
 2729189821776 
 2729189820816
--------
[[1111    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [87]:
import numpy as np
# argmax
data = np.sin(np.random.random(20)).reshape(5,4)
print(data)
print('========')
index = data.argmax(axis=0)#函数取得最大值所对应的变量x
print(index)

data_max = data[index,range(data.shape[1])]#*********
print(data_max)
print('========')

index1 = data.argmax(axis=1)
print(index1)
data_max1 = data[range(data.shape[1]),index]
print(data_max1)

[[0.68526153 0.10826298 0.77708424 0.00506549]
 [0.72857183 0.23445447 0.58685091 0.15961249]
 [0.62407403 0.82797779 0.23882508 0.67638185]
 [0.78694161 0.27191653 0.6514673  0.45961812]
 [0.59849338 0.44711297 0.18071968 0.07460788]]
[3 2 0 2]
[0.78694161 0.82797779 0.77708424 0.67638185]
[2 0 1 0 0]
[0.00506549 0.58685091 0.62407403 0.6514673 ]


In [89]:
import numpy as np
# tile
a = np.arange(0,40,10)
print(a)
print("-----------")
b = np.tile(a,(2,3))#ndrray扩展操作n倍
print(b)

[ 0 10 20 30]
-----------
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [90]:
import numpy as np
# 排序sort
a = np.array([
			[4,3,5],
			[1,2,1]
			])
print(a)
print('========')
b = np.sort(a,axis=1)#按行排序
print(b)
print('========')
a.sort()#默认按行排序
print(a)
print('========')

c = np.array([4,2,1,3])
d = np.argsort(c)#最小值索引
print(d)
print('========')
print(c[d])

[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]
[[3 4 5]
 [1 1 2]]
[2 1 3 0]
[1 2 3 4]
